services:
  app:
    image: thecodingmachine/php:8.5-v5-apache
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/
    environment:
      APACHE_DOCUMENT_ROOT: ianseo/
      PHP_INI_MAX_EXECUTION_TIME: 240
      PHP_INI_MEMORY_LIMIT: 512M
      PHP_INI_POST_MAX_SIZE: 128M
      PHP_INI_UPLOAD_MAX_FILESIZE: 128M
      PHP_EXTENSIONS: intl gd imagick

  db:
    image: mysql:8.4
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ianseo
      MYSQL_USER: ianseo
      MYSQL_PASSWORD: ianseo
      MYSQL_DATABASE: ianseo

  adminer:
    image: adminer:5
    ports:
      - 8080:8080

volumes:
  db_data:
